# Generated by Django 4.2.7 on 2025-03-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField()),
                ('region', models.CharField(choices=[('Not specified', 'Not specified'), ('Dublin 1', 'Dublin 1'), ('Dublin 2', 'Dublin 2'), ('Dublin 3', 'Dublin 3'), ('Dublin 4', 'Dublin 4'), ('Dublin 5', 'Dublin 5'), ('Dublin 6', 'Dublin 6'), ('Dublin 7', 'Dublin 7'), ('Dublin 8', 'Dublin 8'), ('Dublin 9', 'Dublin 9'), ('Dublin 10', 'Dublin 10'), ('Dublin 11', 'Dublin 11'), ('Dublin 12', 'Dublin 12'), ('Dublin 13', 'Dublin 13'), ('Dublin 14', 'Dublin 14'), ('Dublin 15', 'Dublin 15'), ('Dublin 16', 'Dublin 16'), ('Dublin 17', 'Dublin 17'), ('Dublin 18', 'Dublin 18'), ('Dublin 19', 'Dublin 19'), ('Dublin 20', 'Dublin 20'), ('Dublin 21', 'Dublin 21'), ('Dublin 22', 'Dublin 22'), ('Dublin 23', 'Dublin 23'), ('Dublin 24', 'Dublin 24')], default='Not specified', max_length=15)),
                ('age_group', models.CharField(choices=[('Not specified', 'Not specified'), ('Baby (age 0-1y)', 'Baby (age 0-1y)'), ('Toddler (age 1-3y)', 'Toddler (age 1-3y)'), ('Child (age 4-12y)', 'Child (age 4-12y)'), ('Teenager (age 13-19y)', 'Teenager (age 13-19y)'), ('Young adult (age 16-24)', 'Young adult (age 16-24)'), ('Multiple ages', 'Multiple ages')], default='Not specified', max_length=30)),
            ],
        ),
    ]
