# Generated by Django 4.2.7 on 2025-03-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('type_of_request', models.CharField(choices=[('not specified', 'not specified'), ('Support post', 'Support post'), ('Collaborate', 'Collaborate'), ('General contact', 'General contact')], default='not specified', max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
