# Generated by Django 4.2.7 on 2025-02-21 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('region', models.IntegerField(choices=[(0, 'Not specified'), (1, 'Dublin 1'), (2, 'Dublin 2'), (3, 'Dublin 3'), (4, 'Dublin 4'), (5, 'Dublin 5'), (6, 'Dublin 6'), (7, 'Dublin 7'), (8, 'Dublin 8'), (9, 'Dublin 9'), (10, 'Dublin 10'), (11, 'Dublin 11'), (12, 'Dublin 12'), (13, 'Dublin 13'), (14, 'Dublin 14'), (15, 'Dublin 15'), (16, 'Dublin 16'), (17, 'Dublin 17'), (18, 'Dublin 18'), (19, 'Dublin 19'), (20, 'Dublin 20'), (21, 'Dublin 21'), (22, 'Dublin 22'), (23, 'Dublin 23'), (24, 'Dublin 24')], default=0)),
                ('age_group', models.IntegerField(choices=[(0, 'Not specified'), (1, 'Baby (age 0-1y)'), (2, 'Toddler (age 1-3y)'), (3, 'Child (age 4-12y)'), (4, 'Teenager (age 3-19y)'), (5, 'Young adult (age 16-24)'), (6, 'Multiple ages')], default=0)),
                ('type_of_request', models.IntegerField(choices=[(0, 'not specified'), (1, 'Offering help'), (2, 'Asking help'), (3, 'Sharing tips & tricks')], default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
