# Generated by Django 4.2.7 on 2025-03-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unposted'), (1, 'Posted')], default=0),
        ),
    ]
