# Generated by Django 4.2.7 on 2025-07-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_support_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
