# Generated by Django 4.2.7 on 2025-03-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaboraterequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollaborateRequest',
        ),
    ]
